### ISSUE TITLE
Pitch diagram being drawn more than once in Lessons

### ISSUE THREAD

**Issue by blaketrahan** [Invertex/WaniKani-Pitch-Info#1]
Have only encountered this in lessons. Clicking the play button caused it to draw more as well (second picture). Included inspector for completeness.

<img width="1280" alt="first" src="https://user-images.githubusercontent.com/13410662/29284525-d77d382a-8133-11e7-872f-a940fa806664.png">
<img width="1278" alt="after-clicking-play" src="https://user-images.githubusercontent.com/13410662/29284533-de0c53d8-8133-11e7-9f78-2e444780ba18.png">

**Comment by Invertex** [comment]
Haven't been able to reproduce this issue currently. Is it still happening?

**Comment by blaketrahan** [comment]
No I believe you fixed it in an update.
