### ISSUE TITLE
Inconsistent Pitch Pattern Matrix

### ISSUE THREAD

**Issue by DJTB** [Invertex/WaniKani-Pitch-Info#2]
```
var pitchPatterns = 
    [
        /* 1 kana */[ [0,1], [1,0] ],
        /* 2 kana */[ [0,1,1], [1,0,0], [0,1,0] ],   
        /* 3 kana */[ [0,1,1,1], [1,0,0,0], [0,1,0,0], [0,1,1,0] ],
        /* 4 kana */[ [0,1,1,1,1], [1,0,0,0,0], [0,1,0,0,0], [0,1,1,0,0], [0,1,1,1,0] ],
        /* 5 kana */[ [0,1,1,1,1,1], [1,0,0,0,0,0], [0,1,0,0,0,0], [0,1,1,0,0,0], [0,1,1,1,0,0], [0,1,1,1,1,0] ],
        /* 6 kana */[ [0,1,1,1,1,1,1], [1,0,0,0,0,0,0], [0,1,0,0,0,0,0], [0,1,1,0,0,0,0], [0,1,1,1,0,0,0], [0,1,1,1,1,0,0], [0,1,1,1,1,1,0] ],
        /* 7 kana */[ [0,1,1,1,1,1,1,1], [1,0,0,0,0,0,0,0], [0,1,0,0,0,0,0,0], [0,1,1,0,0,0,0,0], [0,1,1,1,0,0,0,0], [0,1,1,1,1,1,0,0], [0,1,1,1,1,1,1,0], [0,1,1,1,1,1,1,0] ]
    ];
```

The 7 kana group jumps from `[0,1,1,1,0,0,0,0]` to `[0,1,1,1,1,1,0,0]`, resulting in a repetition of `[0,1,1,1,1,1,1,0]` for the final 2 entries.

**Comment by DJTB** [comment]
I've been cannabalising this for KaniWani, and went with the approach of generating patterns instead to ensure their validity. If illegal moraCount/pitchNum are passed the builders return an empty array. With the empty arrays you can least easily prevent or identify the following bugs:

Current implementation referring to the pitch matrix can fail hard:
https://www.wanikani.com/vocabulary/一生懸命
Or create invalid patterns:
https://www.wanikani.com/vocabulary/小学生
*nakadaka **must** rise on the second mora, there cannot be two low mora at the start*

If you want to use the same functionality, here's a gist with the relevant parts:
https://gist.github.com/DJTB/e9ea9c9e0a56f1b24b44f46113be715f

I've omitted svg generation since I'm doing that with react + recharts, but happy to link it up later when finished.

**Comment by Invertex** [comment]
Super late reply, been very busy with work crunch, hopefully I can get around to look at your work soon, thanks for sharing!

**Comment by DJTB** [comment]
Oh, I just realised that the https://www.wanikani.com/vocabulary/小学生 example I gave might not be a bug per se.

Mine combines digraphs: しょ・う・りゃ・く
Whereas yours appears to be  し・ょ・う・り・ゃ・く

Technically the pattern displayed on WK still rises on the second mora, it just looks like the third if you don't mentally combine the し・ょ

**Comment by DJTB** [comment]
If you ever need it, I ended up extracting it into a module:
[Hatsuon Repo](https://github.com/DJTB/hatsuon)

Keeping in mind that the svg builder in WaniKani-Pitch-Info does expect a slightly different format (see above comment regarding digraphs).
